---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is an agent required, agent supported locations, restricted mode, private mode, dark site, permissions, multiple agents, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: 您可以使用控制台代理将NetApp Console连接到您的基础架构，并安全地协调跨 AWS、Azure、Google Cloud 或本地环境的存储解决方案，以及使用数据保护服务。 
---
= 了解NetApp Console代理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用控制台代理将NetApp Console连接到您的基础架构，并安全地协调跨 AWS、Azure、Google Cloud 或本地环境的存储解决方案，以及使用数据保护服务。

控制台代理使您能够：

* 通过NetApp Console协调存储管理任务，例如配置Cloud Volumes ONTAP、设置存储卷、使用数据分类等等。
* 使用云提供商的 IAM 角色进行身份验证，以实现订阅计费集成。
* 使用高级数据服务（NetApp Backup and Recovery、 NetApp Disaster Recovery、 NetApp Ransomware Resilience和NetApp Cloud Tiering）


如果您不需要高级业务流程或数据保护服务，则无需部署代理即可集中管理本地 ONTAP 群集和云原生存储服务。一些监控和数据移动工具也可以在没有代理的情况下使用。

下表显示了您可以使用和不使用控制台代理时可以使用的功能和服务。

[cols="40,20a,20a"]
|===
|  | 可联系经纪人获取信息 | 无需代理即可购买 


3+| 支持的存储系统： 


| 适用于ONTAP 的Amazon FSx  a| 
是的（发现和管理功能）
 a| 
是的（仅限探索）



| Amazon S3 存储  a| 
是
 a| 
否



| Azure Blob 存储  a| 
是
 a| 
是



| Azure NetApp Files  a| 
是
 a| 
是



| Cloud Volumes ONTAP  a| 
是
 a| 
否



| E系列系统  a| 
是
 a| 
否



| Google Cloud NetApp Volumes  a| 
是
 a| 
是



| Google Cloud 存储桶  a| 
是
 a| 
否



| StorageGRID系统  a| 
是
 a| 
否



| 本地部署ONTAP集群（高级管理和发现）  a| 
是的（高级管理和发现）
 a| 
否（仅限基本发现）



3+| *存储管理和运行状况服务*： 


| 警报  a| 
是
 a| 
否



| 自动化中心  a| 
是
 a| 
是



| Digital Advisor（Active IQ）  a| 
是
 a| 
否



| 许可证和订阅管理  a| 
是
 a| 
否



| 经济效益  a| 
是
 a| 
否



| 首页仪表盘指标  a| 
是的^2^
 a| 
否



| 生命周期规划  a| 
是
 a| 
1号



| 可持续性  a| 
是
 a| 
否



| 软件更新  a| 
是
 a| 
是



| NetApp工作负载  a| 
是
 a| 
是



3+| *可用数据服务*： 


| NetApp Backup and Recovery  a| 
是
 a| 
否



| NetApp Data Classification  a| 
是
 a| 
否



| NetApp Cloud Tiering  a| 
是
 a| 
否



| NetApp Copy and Sync  a| 
是
 a| 
否



| NetApp Disaster Recovery  a| 
是
 a| 
否



| NetApp Ransomware Resilience  a| 
是
 a| 
否



| NetApp Volume Caching  a| 
是
 a| 
否

|===
^1^ 无需控制台代理即可查看生命周期规划，但需要控制台代理才能启动操作。

^2^ 主页上的准确指标需要大小合适且配置正确的控制台代理。



== 控制台代理必须始终处于运行状态

控制台代理是NetApp Console的基本组成部分。您（客户）有责任确保相关代理随时处于正常运行和可访问状态。控制台可以处理短暂的代理中断，但您必须快速修复基础设施故障。

本文档受 EULA 管辖。按照文档以外的方式操作产品可能会影响其功能和您的 EULA 权利。



== 支持的位置

您可以在以下位置安装代理：

* Amazon Web Services
* Microsoft Azure
+
在 Azure 中与其管理的Cloud Volumes ONTAP系统位于同一区域的控制台代理。或者，将其部署在 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 区域对"^]。这可确保Cloud Volumes ONTAP及其关联的存储帐户之间使用 Azure Private Link 连接。 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["了解Cloud Volumes ONTAP如何使用 Azure Private Link"^]

* Google Cloud
+
要将控制台和数据服务与 Google Cloud 一起使用，请在 Google Cloud 中部署您的代理。

* 在您的场所




== 与云提供商的沟通

该代理使用 TLS 1.3 与 AWS、Azure 和 Google Cloud 进行所有通信。



== 如何安装控制台代理

您可以直接从控制台、云提供商的市场安装控制台代理，也可以在您自己的 Linux 主机或 VCenter 环境中手动安装软件。

* link:concept-modes.html["了解NetApp Console部署模式"]
* link:task-quick-start-standard-mode.html["开始在标准模式下使用NetApp Console"]
* link:task-quick-start-restricted-mode.html["开始在受限模式下使用NetApp Console"]




== 云提供商权限

您需要特定权限才能直接从NetApp Console创建控制台代理，并且需要另一组权限来创建控制台代理本身。如果您直接从控制台在 AWS 或 Azure 中创建控制台代理，则控制台将使用其所需的权限创建控制台代理。

在标准模式下使用控制台时，如何提供权限取决于您计划如何创建控制台代理。

要了解如何设置权限，请参阅以下内容：

* 标准模式
+
** link:concept-install-options-aws.html["AWS 中的代理安装选项"]
** link:concept-install-options-azure.html["Azure 中的代理安装选项"]
** link:concept-install-options-google.html["Google Cloud 中的代理安装选项"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["为本地部署设置云权限"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["设置限制模式的权限"]


要查看控制台代理日常操作所需的确切权限，请参阅以下页面：

* link:reference-permissions-aws.html["了解控制台代理如何使用 AWS 权限"]
* link:reference-permissions-azure.html["了解控制台代理如何使用 Azure 权限"]
* link:reference-permissions-gcp.html["了解控制台代理如何使用 Google Cloud 权限"]


您有责任在后续版本中添加新权限时更新控制台代理策略。发行说明列出了新的权限。



== 代理升级

NetApp每月更新代理软件以添加功能并提高稳定性。某些控制台功能（如Cloud Volumes ONTAP和本地ONTAP集群管理）依赖于控制台代理版本和设置。

当您在云端安装代理时，如果控制台代理可以访问互联网，则会自动更新。



== 操作系统和虚拟机维护

维护控制台代理主机上的操作系统是您（客户）的责任。例如，您（客户）应按照贵公司的操作系统分发标准程序，对控制台代理主机上的操作系统应用安全更新。

请注意，您（客户）在应用次要安全更新时不需要停止控制台主机上的任何服务。

如果您（客户）需要停止然后启动控制台代理虚拟机，您应该从云提供商的控制台或使用标准的内部管理程序来执行此操作。

<<agents-must-be-operational-at-all-times,控制台代理必须始终处于运行状态>> 。



== 多系统和代理

一个代理可以管理多个系统并在控制台中支持数据服务。您可以根据部署规模和使用的数据服务使用单个代理来管理多个系统。

对于大规模部署，请与您的NetApp代表合作来确定您的环境规模。如果遇到问题，请联系NetApp支持。

以下是代理部署的一些示例：

* 您有一个多云环境（例如，AWS 和 Azure），并且您希望在 AWS 中有一个代理，在 Azure 中有一个代理。每个系统都管理在这些环境中运行的Cloud Volumes ONTAP系统。
* 服务提供商可能使用一个控制台组织为其客户提供服务，同时使用另一个组织为其某个业务部门提供灾难恢复。每个组织都需要自己的代理人。

