---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: console agent, agent, what is an agent, deployment, hybrid cloud, storage management, data services 
summary: Console 代理是您在网络中安装的轻量级软件组件，用于将存储基础架构连接到 NetApp Console。它实现了高级存储编排、数据服务和安全的云集成。 
---
= 了解NetApp Console代理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Console 代理是您在网络中安装的轻量级软件组件，用于将存储基础架构连接到 NetApp Console。它实现了高级存储编排、数据服务和安全的云集成。



== Console 代理的作用

Console 代理弥合了存储系统和 NetApp Console 之间的连接缺口。它将您的基础架构安全地连接到 NetApp API 和 Console，使您可以：

* 从 NetApp Console 发现和监控跨 AWS、Azure、Google Cloud 和本地环境的存储系统。
* 从 NetApp Console 协调存储系统上的存储资源调配和配置任务。
* 使用智能数据保护和管理工作流程。
* 安全跟踪云服务使用情况，并将部署连接到正确的订阅，以实现准确的计费和成本管理。




=== Console Agent 架构

代理使用的轻量级流程具有以下特性：

* 从 Console SaaS 应用程序中提取或推送数据（标准和受限模式）
* 发起所有通信—NetApp Console 从不向代理发起出站调用
* 使用标准管理协议连接到存储系统
* 使用 TLS 1.3 与云提供商和 NetApp Console API 进行安全通信




=== Console 代理可用性和操作要求

Console 代理对 NetApp Console 至关重要。代理必须保持可操作性和可访问性，以实现不间断的管理和数据服务。您有责任确保：

* 代理保持正常运行
* 代理具有到所需端点的网络连接
* 快速解决基础架构故障
* 代理 VM 会根据 NetApp 建议进行维护和升级




== 何时需要 Console 代理

如果要执行以下操作，则需要部署至少一个 Console 代理：

* 使用受限或专用部署模式（Console 安装在您自己的环境中）。可能需要额外的代理才能启用某些服务。
* 访问高级数据服务（NetApp Backup and Recovery、NetApp Disaster Recovery、NetApp Ransomware Resilience、NetApp Data Classification 等）。
* 管理 Cloud Volumes ONTAP 系统。
* 对本地 ONTAP 集群执行高级管理任务。
* 跟踪许可证、监控存储运行状况并规划生命周期升级。


如果没有代理，您可以执行基本的存储发现并访问一组有限的监控和存储管理功能。但是，大多数企业用例需要一个或多个运营代理。

下表显示了哪些存储系统和服务可以使用或不使用 Console 代理。

[cols="40,20a,20a"]
|===
|  | 可联系经纪人获取信息 | 无需代理即可购买 


3+| *支持的存储系统*： 


| 适用于ONTAP 的Amazon FSx  a| 
是的（发现和管理功能）
 a| 
是的（仅限探索）



| Amazon S3 存储  a| 
是
 a| 
否



| Azure Blob 存储  a| 
是
 a| 
是



| Azure NetApp Files  a| 
是
 a| 
是



| Cloud Volumes ONTAP  a| 
是
 a| 
否



| E系列系统  a| 
是
 a| 
否



| Google Cloud NetApp Volumes  a| 
是
 a| 
是



| Google Cloud 存储桶  a| 
是
 a| 
否



| StorageGRID系统  a| 
是
 a| 
否



| 本地 ONTAP 集群  a| 
是的（高级管理和发现）
 a| 
否（仅限基本发现）



3+| *存储管理和运行状况服务*： 


| 警报  a| 
是
 a| 
否



| 自动化中心  a| 
是
 a| 
是



| Digital Advisor（Active IQ）  a| 
是
 a| 
否



| 许可证和订阅管理  a| 
是
 a| 
否



| 经济效益  a| 
是
 a| 
否



| 首页仪表盘指标  a| 
是的。准确的主页指标需要适当大小和配置的 Console 代理。
 a| 
否



| 生命周期规划  a| 
是
 a| 
不可以。您可以在没有 Console 代理的情况下查看生命周期规划，但需要 Console 代理才能启动操作。



| 可持续性  a| 
是
 a| 
否



| 软件更新  a| 
是
 a| 
是



| NetApp工作负载  a| 
是
 a| 
是



3+| *可用数据服务*： 


| NetApp Backup and Recovery  a| 
是
 a| 
否



| NetApp Data Classification  a| 
是
 a| 
否



 a| 
NetApp Cloud Tiering*
 a| 
是
 a| 
否



| NetApp Copy and Sync  a| 
是
 a| 
否



| NetApp Disaster Recovery  a| 
是
 a| 
否



| NetApp Ransomware Resilience  a| 
是
 a| 
否



| NetApp Volume Caching  a| 
是
 a| 
否

|===
[NOTE]
====
自 2026 年 4 月 26 日起，NetApp Cloud Tiering 不再可供购买或续订许可证。

现有客户可以继续使用并获得 NetApp Cloud Tiering 支持，直至其订阅或许可合同到期。订阅到期后，客户将无法再访问 NetApp Cloud Tiering 功能或支持。

NetApp 建议客户与其 NetApp 代表合作，将其现有分层许可证转换为 ONTAP FabricPool 许可证，该许可证提供 ONTAP 中数据分层的功能。有关如何在 ONTAP 中使用 FabricPool 设置数据分层的更多信息，请参见 link:https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["在 ONTAP 集群上安装 FabricPool 许可证"]。

* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-Notice2.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_9L2PauNXYE0fOs0RIz8KK2q5Jb6sg8Yv-97NNJ53ceAab9UAqpKOrAvByxsOWqhIQHNCHgFfM0q3TI["NetApp Cloud Tiering 停止提供通知"]
* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-FAQ-v3.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_rplJe_ZtlY4PQAQRQlewsDa0W4JR55muT0KCThR46zI7-uOhIYfVsxODDKFrnYYvy5uZzvhEKHOwBI["NetApp Cloud Tiering 停止可用性常见问题解答"]


====
link:concept-modes.html["了解NetApp Console部署模式"] 了解何时需要代理以及代理启用的功能。



== Console 代理的部署选项

可以在以下位置部署 Console 代理：

* Amazon Web Services
* Microsoft Azure
* Google Cloud
+
要管理 Google Cloud 资源，请在 Google Cloud 中部署代理。本地代理无法管理 Google Cloud 资源。

* 在您的场所（仅限标准或私有模式）


您的 Console 部署模式、存储环境和数据主权需求决定了您在何处部署代理。跨环境部署多个代理，以实现组织分离或业务需求。

您可以直接从 Console、云市场，或在 VCenter 或本地手动部署代理。link:concept-agent-install-options.html["比较部署方法，选择适合您环境的方法"].



=== NetApp Console SaaS 应用程序代理（标准模式）

在云或本地部署代理，以连接到云托管的 Console SaaS 应用程序。代理启用高级功能，而 Console UI 仍可从任何地方访问。

使用 SaaS 应用程序（标准模式）时，您可以直接从 Console 安装代理。您可以在 AWS、Azure 或 Google Cloud 中安装，也可以在您自己的 Linux 主机或 VCenter 环境中手动安装。



=== 受限模式下的 NetApp Console 代理

在受限模式下，用户直接从已安装的代理访问 NetApp Console，而不是从云托管的 SaaS 应用程序访问。您必须至少安装一个代理作为 Console 访问点。需要其他代理来启用数据服务和管理存储系统。

从云提供商的市场中安装代理，或通过在云中、本地或 VCenter 环境中的自有 Linux 主机上手动安装软件。



=== 私有模式下的 NetApp Console 代理（内部或云端，无出站连接）

在专用模式下，用户直接从已安装的代理访问 NetApp Console。您必须至少安装一个代理才能用作 Console 访问点。需要其他代理来启用数据服务和管理存储系统。

在您的数据中心或气隙环境中安装代理。代理与 NetApp API 端点没有连接，所有操作都保持本地状态，具有完全的数据主权和控制权。



=== 在需要时使用多个代理

每个代理独立运行，可以管理多个存储系统和数据服务。在需要时部署多个代理：

* 按存储类型或组织功能隔离
* 地理或网络分段要求


例如：

* 在多云环境中，您可以在 AWS 中部署一个代理，在 Azure 中部署另一个代理。每个代理管理各自环境中的 Cloud Volumes ONTAP 系统。
* 服务提供商可以使用一个 Console 组织为客户提供服务，另一个组织为业务部门提供灾难恢复服务。每个组织都需要自己的代理。




== 控制台代理升级

云中的代理在具有出站互联网访问权限时会自动升级。对于无法访问互联网的代理（专用模式），请参阅 link:task-upgrade-agent.html["管理控制台代理升级"] 手动升级说明。
