---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: _控制台代理_是在您的云网络或本地网络上运行的NetApp软件。您可以使用控制台代理将NetApp控制台服务连接到您的存储环境。 
---
= 了解NetApp控制台代理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
_控制台代理_在您的云网络或本地网络中运行。您可以使用控制台代理将NetApp控制台服务连接到您的存储环境。



== 没有控制台代理您可以做什么

如果您不部署控制台代理，则某些控制台功能和服务可用：

* Amazon FSx for NetApp ONTAP
+
某些操作需要控制台代理或NetApp Workloads 链接。 https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["了解哪些操作需要控制台代理或链接"^]

* 自动化中心
* Azure NetApp Files
+
您不需要控制台代理来管理Azure NetApp Files，但需要使用NetApp数据分类来扫描Azure NetApp Files。

* Google Cloud NetApp Volumes
* NetApp复制和同步
* 数字顾问
* 监控许可证使用情况，订阅监控需要控制台代理
+
通常，您无需使用控制台代理即可向NetApp控制台添加许可证。

+
需要代理来添加Cloud Volumes ONTAP _基于节点的_许可证，因为数据来自安装在Cloud Volumes ONTAP系统上的许可证。

* 直接发现本地ONTAP集群
+
您不需要控制台代理即可将本地ONTAP集群添加到控制台，但需要控制台代理来添加其他控制台功能和数据服务。

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["了解有关本地ONTAP集群的发现和管理选项的更多信息"^]

* 软件更新
* 可持续性
* NetApp工作负载




== 当需要控制台代理时

在标准模式下，控制台需要控制台代理来执行以下操作：

* 警报
* Amazon FSx for ONTAP管理功能
* Amazon S3 存储
* Azure Blob 存储
* NetApp备份和恢复
* 数据分类
* Cloud Volumes ONTAP
* NetApp灾难恢复
* E系列系统
* 经济效率^1^
* Google Cloud Storage 存储桶
* 本地ONTAP集群与NetApp数据服务的集成
* NetApp勒索软件抵御能力
* StorageGRID系统
* NetApp云分层
* NetApp卷缓存


^1^ 您无需控制台代理即可访问这些服务，但需要控制台代理来启动操作。

您始终需要一个控制台代理才能在受限模式下使用控制台。



== 控制台代理必须始终处于运行状态

控制台代理是NetApp控制台的基本组成部分。您（客户）有责任确保相关代理随时处于正常运行和可访问状态。控制台可以处理短暂的代理中断，但您必须快速修复基础设施故障。

本文档受 EULA 管辖。按照文档以外的方式操作产品可能会影响其功能和您的 EULA 权利。



== 支持的位置

您可以在以下位置安装代理：

* Amazon Web Services
* Microsoft Azure
+
在 Azure 中与其管理的Cloud Volumes ONTAP系统位于同一区域的控制台代理。或者，将其部署在 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 区域对"^]。这可确保Cloud Volumes ONTAP及其关联的存储帐户之间使用 Azure Private Link 连接。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["了解Cloud Volumes ONTAP如何使用 Azure Private Link"^]

* Google Cloud
+
要将控制台和数据服务与 Google Cloud 一起使用，请在 Google Cloud 中部署您的代理。

* 在您的场所




== 与云提供商的沟通

该代理使用 TLS 1.3 与 AWS、Azure 和 Google Cloud 进行所有通信。



== 限制模式

要在受限模式下使用控制台，请安装控制台代理并访问在控制台代理上本地运行的控制台界面。

link:concept-modes.html["了解NetApp控制台部署模式"] 。



== 如何安装控制台代理

您可以直接从控制台、云提供商的市场安装控制台代理，也可以在您自己的 Linux 主机或 VCenter 环境中手动安装软件。如何开始取决于您是在标准模式还是受限模式下使用控制台。

* link:concept-modes.html["了解NetApp控制台部署模式"]
* link:task-quick-start-standard-mode.html["开始在标准模式下使用NetApp控制台"]
* link:task-quick-start-restricted-mode.html["开始在受限模式下使用NetApp控制台"]




== 云权限

您需要特定权限才能直接从NetApp控制台创建控制台代理，并且需要另一组权限来创建控制台代理实例本身。如果您直接从控制台在 AWS 或 Azure 中创建控制台代理，则控制台将使用其所需的权限创建控制台代理。

在标准模式下使用控制台时，如何提供权限取决于您计划如何创建控制台代理。

要了解如何设置权限，请参阅以下内容：

* 标准模式
+
** link:concept-install-options-aws.html["AWS 中的代理安装选项"]
** link:concept-install-options-azure.html["Azure 中的代理安装选项"]
** link:concept-install-options-google.html["Google Cloud 中的代理安装选项"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["为本地部署设置云权限"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["设置限制模式的权限"]


要查看控制台代理日常操作所需的确切权限，请参阅以下页面：

* link:reference-permissions-aws.html["了解控制台代理如何使用 AWS 权限"]
* link:reference-permissions-azure.html["了解控制台代理如何使用 Azure 权限"]
* link:reference-permissions-gcp.html["了解控制台代理如何使用 Google Cloud 权限"]


您有责任在后续版本中添加新权限时更新控制台代理策略。发行说明列出了新的权限。



== 代理升级

NetApp每月更新代理软件以添加功能并提高稳定性。某些控制台功能（如Cloud Volumes ONTAP和本地ONTAP集群管理）依赖于控制台代理版本和设置。

在标准或受限模式下，如果控制台代理可以访问互联网，它将自动更新。



== 操作系统和虚拟机维护

维护控制台代理主机上的操作系统是您（客户）的责任。例如，您（客户）应按照贵公司的操作系统分发标准程序，对控制台代理主机上的操作系统应用安全更新。

请注意，您（客户）在应用次要安全更新时不需要停止控制台主机上的任何服务。

如果您（客户）需要停止然后启动控制台代理虚拟机，您应该从云提供商的控制台或使用标准的内部管理程序来执行此操作。

<<agents-must-be-operational-at-all-times,控制台代理必须始终处于运行状态>> 。



== 多系统和代理

一个代理可以管理多个系统并在控制台中支持数据服务。您可以根据部署规模和使用的数据服务使用单个代理来管理多个系统。

对于大规模部署，请与您的NetApp代表合作来确定您的环境规模。如果遇到问题，请联系NetApp支持。

以下是代理部署的一些示例：

* 您有一个多云环境（例如，AWS 和 Azure），并且您希望在 AWS 中有一个代理，在 Azure 中有一个代理。每个系统都管理在这些环境中运行的Cloud Volumes ONTAP系统。
* 服务提供商可能使用一个控制台组织为其客户提供服务，同时使用另一个组织为其某个业务部门提供灾难恢复。每个组织都需要自己的代理人。

