---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management, bluexp 
summary: 为用户分配平台角色，以授予管理NetApp Console、分配角色、添加用户、创建控制台代理和管理联合的权限。 
---
= NetApp Console平台访问角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
为用户分配平台角色，以授予管理NetApp Console、分配角色、添加用户、创建控制台代理和管理联合的权限。

.大型跨国组织的组织角色示例
XYZ 公司按地区（北美、欧洲和亚太地区）组织数据存储访问，从而提供区域控制和集中监督。

XYZ 公司控制台中的*组织管理员*为每个区域创建一个初始组织和单独的文件夹。每个区域的*文件夹或项目管理员*在该区域的文件夹中组织项目（及相关资源）。

具有“文件夹或项目管理员”角色的区域管理员通过添加资源和用户来主动管理他们的文件夹。这些区域管理员还可以添加、删除或重命名他们管理的文件夹和项目。*组织管理员*继承任何新资源的权限，保持整个组织的存储使用情况的可见性。

在同一个组织内，一名用户被分配了*联合管理员*角色来管理该组织与其企业 IdP 的联合。该用户可以添加或删除联合组织，但不能管理组织内的用户或资源。*组织管理员*为用户分配*联合查看者*角色，以检查联合状态并查看联合组织。

下表列出了每个控制台平台角色可以执行的操作。



== 组织管理角色

[cols="2,1,1"]
|===
| 任务 | 组织管理员 | 文件夹或项目管理员 


| 创建代理 | 是 | 否 


| 从控制台创建、修改或删除系统（添加或发现系统） | 是 | 是 


| 创建文件夹和项目，包括删除 | 是 | 否 


| 重命名现有文件夹和项目 | 是 | 是 


| 分配角色并添加用户 | 是 | 是 


| 将资源与文件夹和项目关联 | 是 | 是 


| 将代理与文件夹和项目关联 | 是 | 否 


| 从文件夹和项目中删除代理 | 是 | 否 


| 管理代理（编辑证书、设置等） | 是 | 否 


| 从管理 > 凭证管理凭证 | 是 | 是 


| 创建、管理和查看联合 | 是 | 否 


| 通过控制台注册支持并提交案例 | 是 | 是 


| 使用与显式访问角色无关的数据服务 | 是 | 是 


| 查看审核页面和通知 | 是 | 是 
|===


== 联盟角色

[cols="2,1,1"]
|===
| 任务 | 联盟管理员 | 联邦查看器 


| 创建联盟 | 是 | 否 


| 验证域名 | 是 | 否 


| 将域添加到联合 | 是 | 否 


| 禁用和删除联盟 | 是 | 否 


| 测试联盟 | 是 | 否 


| 查看联盟及其详细信息 | 是 | 是 
|===


== 合作伙伴角色

[cols="2,1,1"]
|===
| 任务 | 合作伙伴管理员 | 合作伙伴查看器 


| 可以建立合作关系 | 是 | 否 


| 为合作伙伴成员分配角色 | 是 | 否 


| 可以向合作关系添加成员 | 是 | 否 


| 可以查看组织合作关系详细信息 | 是 | 是 
|===


== 超级管理员和查看者角色

*超级管理员*角色提供管理控制台功能、存储和数据服务的完全访问权限。这个角色适合那些监督行政和治理的人。相比之下，“超级查看者”角色提供只读访问权限，非常适合需要查看信息而不进行更改的审计员或利益相关者。

组织应谨慎使用*超级管理员*访问权限，以最大限度地降低安全风险并符合最小特权原则。大多数组织应该分配具有必要权限的细粒度角色，以降低风险并提高可审计性。

.超级角色示例
ABC 公司拥有一个由五人组成的小团队，利用NetApp Console进行数据服务和存储管理。他们没有分配多个角色，而是将“超级管理员”角色分配给两名高级团队成员，由他们负责所有管理任务，包括用户管理和资源配置。其余三名团队成员被分配了*超级查看者*角色，允许他们监控存储健康和数据服务状态，但无法修改设置。

[cols="2,1"]
|===
| 角色 | 继承的角色 


 a| 
超级管理员
 a| 
* 组织管理员
* 文件夹或项目管理员
* 联盟管理员
* 合作伙伴管理员
* 勒索软件抵御能力管理员
* 灾难恢复管理员
* 备份超级管理员
* 存储管理员
* Keystone管理员
* Google Cloud NetApp Volumes管理员




 a| 
超级观众
 a| 
* 组织查看器
* 联邦查看器
* 合作伙伴查看器
* 勒索软件恢复力查看器
* 灾难恢复查看器
* 备份查看器
* 存储查看器
* Keystone查看器
* Google Cloud NetApp Volumes查看器


|===