---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: agent maintenance console, agent troubleshooting, network connectivity validation, agent validation, hardware requirements, deployment readiness, operational compliance, installation troubleshooting 
summary: 您可以使用控制台代理维护控制台来验证控制台代理的安装和配置。 
---
= 使用 NetApp Console 中的维护控制台进行控制台代理验证
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用控制台代理维护控制台来验证控制台代理的安装和配置。



== 访问代理维护控制台

您可以从 Console 代理主机访问维护控制台。导航到以下目录：

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== 配置检查器验证

这 `config-checker validate`该命令允许您验证控制台代理的配置。



=== 参数

`--services <comma-separated list of services to validate>` - *必需的* - 

[role="quick-margin-para"]
选择一个或多个要验证的服务。有效的服务名称是：

* `PLATFORM` 它验证到所需 Console 端点的网络连接，以及 Console 代理所需的端口是否已打开。


`--validationTypes <comma-separated list of validation types to run>` --*必填*-- 从一个或多个要运行的验证类型中进行选择。有效的验证类型为：

* `NETWORK` 验证到所需 Console 端点的网络连接。
* `HARDWARE` 验证代理主机是否满足 Console 代理的最低硬件要求。
+

NOTE: 在安装过程中，NetApp 检查代理主机是否具有至少 80% 的总可用磁盘空间，其中包括 48 GB 在 `/opt`和 32 GB 在 `/var`（总共 80 GB）。安装后，它需要至少 20% 的总磁盘保持可用，其中包括 12 GB 在 `/opt`和 8 GB 在 `/var`（总共 20 GB）。



`--proxy <url>` - *选修的* - 

[role="quick-margin-para"]
指定用于验证的代理服务器 URL。如果您的代理配置为使用代理服务器，则此项为必填项。

`--certs <paths>` - *选修的* - 

[role="quick-margin-para"]
指定用于验证的一个或多个证书文件的路径。证书文件必须为PEM格式。多个路径之间用逗号分隔。如果您的代理使用自定义证书，则此参数为必填项。



=== 配置检查器验证示例

以下示例包括验证网络连接、所需端口和硬件要求，以及使用代理服务器和自定义证书的不同组合。

.验证网络连接和硬件要求：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.使用代理服务器作为代理时的验证：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.使用证书验证代理：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== 查看任何命令的帮助

要查看任何命令的帮助，请附加 `--help`到命令。例如，要查看 `proxy add`命令，使用以下命令：

[source, cli]
----
./agent-maint-console proxy add --help
----