---
sidebar: sidebar 
permalink: task-sign-up-saas.html 
keywords: sign up, signing up, sign in, signing in, login with netapp, log in with netapp, create account, account, log in with nss, nss, nss login 
summary: 要开始使用控制台，第一步是使用您的NetApp支持站点凭据注册或登录，或者创建NetApp Console登录帐户。如果您是公司第一个注册的用户，您将在控制台中以组织管理员的身份创建一个新组织。如果贵公司已有组织机构，您可以注册或登录以访问该机构。 
---
= 注册或登录NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用控制台，请注册或使用您的NetApp支持站点凭据登录，或者创建NetApp Console登录。如果您是公司第一个注册的人，您将创建一个新的组织并担任管理员。如果贵公司已有组织，请使用您现有的NetApp支持站点凭据或公司单点登录 (SSO) 注册或登录。



[[sign-up-for-netapp-console-as-the-initial-organization-administrator]]
== 以初始组织管理员身份注册NetApp Console

如果贵公司还没有NetApp Console组织，请注册创建一个。第一个用户将成为组织管理员，并管理用户帐户和权限。您可以稍后更新角色并添加更多管理员。

.步骤
. 打开 Web 浏览器并转到 https://console.netapp.com["NetApp Console"^]。
. 如果您拥有NetApp支持站点帐户，请直接在“登录”页面上输入与您的帐户关联的电子邮件地址。
+
控制台会在您首次登录时使用您的NetApp支持站点凭据进行注册。

. 如果您想通过创建控制台登录来注册，请选择*注册*。
+
.. 在*注册*页面上，输入所需信息并选择*下一步*。
+

NOTE: 注册表格中只允许使用英文字符。

.. 检查您的收件箱，查找来自NetApp的电子邮件，其中包含验证您的电子邮件地址的说明。
+
请验证您的电子邮件地址以完成注册。



. 登录后，请阅读并接受最终用户许可协议。
. 在“欢迎”页面上，创建一个组织。
. 选择*让我们开始吧*。


+ 作为首次用户和组织管理员，您可以按照引导流程添加存储资源、创建控制台代理等等。 link:task-console-assistant.html["了解如何使用控制台助手。"^]

.下一步
作为管理员，在完成控制台助手中包含的步骤后，您应该规划身份和访问策略，将用户添加到您的组织，并分配角色。 link:task-iam-get-started.html["了解NetApp Console的身份和访问管理"^]



[[sign-up-or-login-to-netapp-console-when-an-organization-already-exists]]
== 如果组织已存在，请注册或登录NetApp Console。

如果贵公司已有NetApp Console组织，请注册或登录以访问它。您的注册或登录方式取决于您的公司是否使用身份联合或拥有NetApp支持站点凭据。如果还没有，请创建NetApp Console登录帐户。

.步骤
. 打开 Web 浏览器并转到 https://console.netapp.com["NetApp Console"^]。
. 如果您拥有NetApp支持站点帐户，或者您的公司已设置单点登录 (SSO)，请在“登录”页面上输入您关联的电子邮件地址或 SSO 凭据。按照提示完成登录。
+
在这两种情况下，您都会在初始登录时注册控制台。

. 如果您想通过创建控制台登录来注册，请选择*注册*。
+
.. 在*注册*页面上，输入所需信息并选择*下一步*。
+

NOTE: 注册表格中只允许使用英文字符。

.. 检查您的收件箱，查找来自NetApp的电子邮件，其中包含验证您的电子邮件地址的说明。
+
请验证您的电子邮件地址以完成注册。



. 登录后，请阅读并接受最终用户许可协议。
. 如果系统提示您创建组织，请关闭对话框并告知控制台管理员，以便他们可以将您添加到控制台组织并授予您访问权限。 link:task-user-settings.html#contact-admin["了解如何联系组织管理员。"^]


.下一步
获得组织访问权限后，即可开始管理存储和使用分配给您的数据服务。
