---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: '根据您在控制台中执行的操作，您可能已将ONTAP凭据和NetApp支持站点 (NSS) 凭据与您的用户登录关联。关联这些凭证后，您可以查看和管理它们。例如，如果您更改这些凭据的密码，则需要在控制台中更新密码。' 
---
= 管理与您的NetApp控制台登录关联的凭据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
根据您在控制台中执行的操作，您可能已将ONTAP凭据和NetApp支持站点 (NSS) 凭据与您的用户登录关联。关联这些凭证后，您可以查看和管理它们。例如，如果您更改这些凭据的密码，则需要在控制台中更新密码。



== ONTAP凭据

用户需要ONTAP管理员凭据才能在控制台中发现ONTAP集群。但是， ONTAP系统管理器访问取决于您是否使用控制台代理。

.无需控制台代理
系统会提示用户输入其ONTAP凭据以访问集群的ONTAP系统管理器。用户可以选择将这些凭据保存在控制台中，这意味着他们不必每次都输入这些凭据。用户凭证仅对相应用户可见，并且可以从用户凭证页面进行管理。

.使用控制台代理
默认情况下，不会提示用户输入其ONTAP凭据来访问ONTAP系统管理器。但是，控制台管理员（具有组织管理员角色）可以配置控制台以提示用户输入其ONTAP凭据。启用此设置后，用户每次都需要输入其ONTAP凭据。

link:task-ontap-access-connector.html["了解更多信息。"^]



== NSS 凭证

与您的NetApp控制台登录关联的 NSS 凭据可支持注册、案例管理和访问Digital Advisor。

* 当您访问*支持>资源*并注册支持时，系统会提示您将 NSS 凭据与您的登录名关联。
+
这将注册您的组织或帐户以获得支持并激活支持权利。您的组织中只有一个用户必须将NetApp支持站点帐户与其登录名关联，以注册支持并激活支持权利。完成后，“*资源*”页面将显示您的帐户已注册支持。

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["了解如何注册以获得支持"^]

* 当您访问*管理 > 支持 > 案例管理*时，如果您还没有输入 NSS 凭证，系统会提示您输入。此页面使您能够创建和管理与您的 NSS 帐户和公司相关的支持案例。
* 当您在控制台中访问Digital Advisor时，系统会提示您输入 NSS 凭据登录Digital Advisor 。


请注意与您的登录名关联的 NSS 帐户的以下事项：

* 该帐户在用户级别进行管理，这意味着其他登录的用户无法查看该帐户。
* 每个用户只能有一个与Digital Advisor和支持案例管理关联的 NSS 帐户。
* 如果您尝试将NetApp支持站点帐户与Cloud Volumes ONTAP系统关联，则只能从添加到您所属组织的 NSS 帐户中进行选择。
+
NSS 帐户级凭据与与您的登录关联的 NSS 帐户不同。  NSS 帐户级凭证使您能够使用 BYOL 部署Cloud Volumes ONTAP 、注册 PAYGO 系统并升级其软件。

+
link:task-adding-nss-accounts.html["了解有关将 NSS 凭据与您的NetApp控制台组织或帐户结合使用的更多信息"] 。





== 管理您的用户凭证

通过更新用户名和密码或删除凭证来管理您的用户凭证。

.步骤
. 选择“*管理 > 凭证*”。
. 选择*用户凭证*。
. 如果您还没有任何用户凭证，您可以选择*添加 NSS 凭证*来添加您的NetApp支持站点帐户。
. 通过从“操作”菜单中选择以下选项来管理现有凭据：
+
** *更新凭据*：更新帐户的用户名和密码。
** *删除凭据*：删除与您的控制台登录关联的 NSS 帐户。



