---
sidebar: sidebar 
permalink: task-federation-ping.html 
keywords: PingFederate, BlueXP, federation, single sign-on, SSO, identity provider, IdP, service provider-initiated SSO, X.509 certificate, Audience ID, Entity ID, Reply URL, organization admin 
summary: '与您的 PingFederate IdP 提供商联合，为NetApp Console启用单点登录 (SSO)。这允许用户使用他们的公司凭证登录。' 
---
= 使用 PingFederate 联合NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
与您的 PingFederate IdP 提供商联合，为NetApp Console启用单点登录 (SSO)。这允许用户使用他们的公司凭证登录。

.必需角色
创建和管理联合身份验证需要 Federation 管理员角色。Federation 查看器可以查看 Federation 页面。link:reference-iam-predefined-roles.html["了解有关访问角色的更多信息。"]


NOTE: 您可以与您的企业 IdP 或NetApp支持站点联合。  NetApp建议选择其中一个，但不要同时选择两者。

NetApp仅支持服务提供商发起的（SP发起的） SSO。您需要首先配置身份提供者以信任NetApp作为服务提供商。然后，您可以在控制台中创建使用身份提供者配置的连接。

您可以设置与 PingFederate 的联合连接，以启用 Console 的单点登录 (SSO)。该过程包括将 PingFederate 服务器配置为信任 Console 作为服务提供商，然后在 Console 中创建连接。

.开始之前
* 需要具有管理权限的 IdP 帐户。与您的 IdP 管理员协调以完成这些步骤。
* 标识要用于联合的域。您可以使用电子邮件域名或您拥有的其他域名。如果要使用电子邮件域名以外的域名，必须首先在 Console 中验证该域名。有关说明，请参阅 link:task-federation-verify-domain.html["在NetApp Console中验证您的域"]。


.步骤
. 选择*管理>身份和访问*。
. 选择“*Federation*”以查看“*Federations*”页面。
. 选择*配置新联合*。
. 输入您的域名详细信息：
+
.. 选择您是否要使用已验证的域名或您的电子邮件域名。电子邮件域是与您登录的帐户关联的域。
.. 输入您正在配置的联盟的名称。
.. 如果您选择已验证的域，请从列表中选择该域。


. 选择“下一步”。
. 对于您的连接方法，选择*提供商*，然后选择*PingFederate*。
. 选择“下一步”。
. 配置您的 PingFederate 服务器以信任NetApp作为服务提供商。您需要在 PingFederate 服务器上执行此步骤。
+
.. 配置 PingFederate 以信任NetApp Console时，请使用以下值：
+
*** 对于 *回复 URL* 或 *断言消费者服务 (ACS) URL*，使用 `https://netapp-cloud-account.auth0.com/login/callback`
*** 对于*注销 URL*，使用 `https://netapp-cloud-account.auth0.com/logout`
*** 对于 *Audience/Entity ID*，请使用  `urn:auth0:netapp-cloud-account:<fed-domain-name-pingfederate>`，其中 <fed-domain-name-pingfederate> 是联盟的域名。例如，如果您的域是  `example.com`，则 Audience/Entity ID 应为  `urn:auth0:netapp-cloud-account:fed-example-com-pingfederate`。


.. 复制 PingFederate 服务器 URL。在控制台中创建连接时，您将需要此 URL。
.. 从您的 PingFederate 服务器下载 X.509 证书。它需要采用 Base64 编码的 PEM 格式（.pem、.crt、.cer）。


. 返回控制台，然后选择“下一步”来创建连接。
. 使用 PingFederate 创建连接。
+
.. 输入您在上一步中复制的 PingFederate 服务器 URL。
.. 上传 X.509 签名证书。证书必须采用 PEM、CER 或 CRT 格式。


. 选择*创建连接*。系统在几秒钟内建立连接。
. 选择“下一步”。
. 选择*测试连接*来测试您的连接。您将被引导至 IdP 服务器的登录页面。使用您的身份提供商凭据登录。登录后，返回控制台启用连接。
+

NOTE: 在受限模式下使用控制台时，请将 URL 复制到隐身浏览器窗口或单独的浏览器中，以登录到您的身份提供商 (IdP)。

. 在控制台中，选择“下一步”以查看摘要页面。
. 设置通知。
+
从 7 天到 30 天之间进行选择。系统通过电子邮件向具有以下角色的任何用户发送过期通知，并将其显示在 Console 中：Super admin、Org admin、Federation admin 和 Federation viewer。

. 查看联盟详细信息，然后选择“启用联盟”。
. 选择“*完成*”以完成该过程。


启用联合身份验证后，用户可以使用其企业凭据登录NetApp Console。
