= 连接器 3.9.52
:allow-uri-read: 




=== 连接器 3.9.52

BlueXP Connector 的此版本包括一些小的安全改进和错误修复，以及一些额外的更新。

目前，3.9.52 版本适用于标准模式和限制模式。



==== 支持 Docker 27 和 Docker 28

连接器现在支持 Docker 27 和 Docker 28。



==== Cloud Volumes ONTAP

当连接器不合规或停机超过 14 天时， Cloud Volumes ONTAP节点不再关闭。当Cloud Volumes ONTAP失去对连接器的访问权限时，它仍会发送事件管理消息。此更改是为了确保即使连接器长时间处于关闭状态， Cloud Volumes ONTAP仍可继续运行。它不会改变连接器的合规性要求。



=== BlueXP中提供Keystone管理

BlueXP中的NetApp Keystone测试版增加了对Keystone管理的访问权限。您可以从BlueXP左侧导航栏访问NetApp Keystone测试版的注册页面。



=== BlueXP身份和访问管理（IAM）



==== 新的存储管理角色

存储管理员、系统健康专家和存储查看器角色可用，可以分配给用户。

这些角色使您能够管理组织中的谁可以发现和管理存储资源，以及查看存储健康信息和执行软件更新。

这些角色支持控制对以下存储资源的访问：

* E系列系统
* StorageGRID系统
* 本地ONTAP系统


您还可以使用这些角色来控制对以下BlueXP服务的访问：

* 软件更新
* 数字顾问
* 运营弹性
* 经济效益
* 可持续性


已添加以下角色：

* *存储管理员*
+
管理组织内存储资源的存储健康、治理和发现。该角色还可以对存储资源执行软件更新。

* *系统健康专家*
+
管理组织内存储资源的存储健康和治理。该角色还可以对存储资源执行软件更新。此角色不能修改或删除工作环境。

* *存储查看器*
+
查看存储健康信息和治理数据。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解访问角色。"^]


