= 
:allow-uri-read: 


.开始之前
您应该具有以下内容：

* 安装控制台代理的 root 权限。
* 如果控制台代理需要代理才能访问互联网，则提供有关代理服务器的详细信息。
+
您可以选择在安装后配置代理服务器，但这样做需要重新启动 Console 代理。

* 如果代理服务器使用 HTTPS 或代理是拦截代理，则需要 CA 签名的证书。



NOTE: 手动安装控制台代理时，无法为透明代理服务器设置证书。如果需要为透明代理服务器设置证书，则必须在安装后使用维护控制台。详细了解link:reference-agent-maint-console-proxy.html["代理维护控制台"]。

.关于此任务
安装后，如果有新版本可用，控制台代理会自动更新。

.步骤
. 如果主机上设置了 _http_proxy_ 或 _https_proxy_ 系统变量，请将其删除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不删除这些系统变量，安装将失败。

. 下载控制台代理软件，然后将其复制到 Linux 主机。您可以从NetApp Console或NetApp支持网站下载。
+
** NetApp Console：转到 *Agents > Management > Deploy agent > On-prem > Manual install*。
+
选择下载代理安装程序文件或文件的 URL。

** https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["NetApp 支持站点"^] （如果您还没有 Console 的访问权限，则需要此选项）。
+

NOTE: 下载适用于您的网络或云端的"在线"代理安装程序。Console 代理可使用单独的"脱机"安装程序，但它仅受专用模式部署支持。

** NetApp 支持站点（如果您还没有 Console 的访问权限，则需要该站点） https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["NetApp 支持站点"^]。


. 分配运行脚本的权限。
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
其中 <version> 是您下载的控制台代理的版本。

. 如果在政府云环境中安装，请禁用配置检查。link:task-troubleshoot-agent.html#disable-config-check["了解如何禁用手动安装的配置检查。"]
. 运行安装脚本。
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
如果您的网络需要代理才能访问互联网，则需要添加代理信息。您可以在安装过程中添加显式代理。 `--proxy` 和  `--cacert` 参数是可选的，系统不会提示您添加它们。如果您有显式代理服务器，则需要输入如图所示的参数。

+

NOTE: 如果要配置透明代理，可以在安装后进行此操作。link:reference-agent-maint-console-proxy.html["了解代理维护控制台"].

+
以下是使用 CA 签名证书配置显式代理服务器的示例：

+
[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy` 使用以下格式之一将 Console 代理配置为使用 HTTP 或 HTTPS 代理服务器：

+
** \http://地址:端口
** \http://用户名:密码@地址:端口
** \http://域名%92用户名:密码@地址:端口
** \https://地址:端口
** \https://用户名:密码@地址:端口
** \https://域名%92用户名:密码@地址:端口
+
请注意以下事项：

+
*** 用户可以是本地用户或域用户。
*** 对于域用户，您必须使用 \ 的 ASCII 代码，如上所示。
*** Console 代理不支持包含 @ 字符的用户名或密码。
*** 如果密码包含以下任何特殊字符，则必须在该特殊字符前面加上反斜杠来转义该特殊字符：& 或 !
+
例如：

+
\http://bxpproxyuser:netapp1\!@地址:3128





. 如果您使用 Podman，则需要调整 aardvark-dns 端口。
+
.. 通过 SSH 连接到控制台代理虚拟机。
.. 打开 podman _/usr/share/containers/containers.conf_ 文件并修改 Aardvark DNS 服务的选定端口。例如，将其更改为54。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
例如：

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. 重新启动控制台代理虚拟机。




. 等待安装完成。
+
安装结束时，如果您指定了代理服务器，控制台代理服务 (occm) 将重新启动两次。

+

NOTE: 如果安装失败，您可以查看安装报告和日志来帮助您解决问题。link:task-troubleshoot-agent.html#troubleshoot-installation["了解如何解决安装问题。"]

. 从连接到控制台代理虚拟机的主机打开 Web 浏览器并输入以下 URL：
+
https://_ipaddress_[]

. 登录后，设置控制台代理：
+
.. 指定与控制台代理关联的组织。
.. 输入系统的名称。
.. 在*您是否在安全环境中运行？*下保持限制模式处于禁用状态。
+
您应该保持限制模式处于禁用状态，因为这些步骤描述了如何在标准模式下使用控制台。仅当您拥有安全的环境并希望断开此帐户与后端服务的连接时，才应启用受限模式。如果真是这样的话，link:task-quick-start-restricted-mode.html["按照步骤在受限模式下开始使用NetApp Console"] 。

.. 选择*让我们开始吧*。



