= 
:allow-uri-read: 


根据您的操作系统，安装代理之前需要 Podman 或 Docker Engine。

* Red Hat Enterprise Linux 8 和 9 需要 Podman。
+
<<podman-versions,查看支持的 Podman 版本>> 。

* Ubuntu 需要 Docker 引擎。
+
<<podman-versions,查看支持的 Docker Engine 版本>> 。



.步骤
[role="tabbed-block"]
====
.Podman
--
按照以下步骤安装和配置 Podman：

* 启用并启动 podman.socket 服务
* 安装python3
* 安装 podman-compose 包版本 1.0.6
* 将 podman-compose 添加到 PATH 环境变量
* 如果使用 Red Hat Enterprise Linux，请验证您的 Podman 版本使用的是 Netavark Aardvark DNS 而不是 CNI



NOTE: 安装代理后调整 aardvark-dns 端口（默认值：53），以避免 DNS 端口冲突。按照说明配置端口。

.步骤
. 如果主机上安装了 podman-docker 包，请将其删除。
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. 安装 Podman。
+
您可以从官方 Red Hat Enterprise Linux 存储库获取 Podman。

+
对于 Red Hat Enterprise Linux 9：

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
其中 <version> 是您正在安装的 Podman 支持的版本。<<podman-versions,查看支持的 Podman 版本>> 。

+
对于 Red Hat Enterprise Linux 8：

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
其中 <version> 是您正在安装的 Podman 支持的版本。<<podman-versions,查看支持的 Podman 版本>> 。

. 启用并启动 podman.socket 服务。
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. 安装 python3。
+
[source, cli]
----
sudo dnf install python3
----
. 如果您的系统上还没有 EPEL 存储库包，请安装它。
. 如果使用 Red Hat Enterprise：
+
此步骤是必需的，因为 podman-compose 可从 Extra Packages for Enterprise Linux (EPEL) 存储库中获得。

+
对于 Red Hat Enterprise Linux 9：

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
对于 Red Hat Enterprise Linux 8：

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. 安装 podman-compose 包 1.0.6。
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: 使用 `dnf install`命令满足将 podman-compose 添加到 PATH 环境变量的要求。安装命令将 podman-compose 添加到 /usr/bin，它已经包含在 `secure_path`主机上的选项。

. 如果使用 Red Hat Enterprise Linux 8，请验证您的 Podman 版本是否使用带有 Aardvark DNS 的 NetAvark 而不是 CNI。
+
.. 通过运行以下命令检查您的 networkBackend 是否设置为 CNI：
+
[source, cli]
----
podman info | grep networkBackend
----
.. 如果 networkBackend 设置为 `CNI`，你需要将其更改为 `netavark`。
.. 安装 `netavark`和 `aardvark-dns`使用以下命令：
+
[source, cli]
----
dnf install aardvark-dns netavark
----
.. 打开 `/etc/containers/containers.conf`文件并修改 network_backend 选项以使用“netavark”而不是“cni”。


+
如果 `/etc/containers/containers.conf`不存在，请将配置更改为 `/usr/share/containers/containers.conf`。

. 重新启动 podman。
+
[source, cli]
----
systemctl restart podman
----
. 使用以下命令确认 networkBackend 现在已更改为“netavark”：
+
[source, cli]
----
podman info | grep networkBackend
----


--
.Docker 引擎
--
按照 Docker 的文档安装 Docker Engine。

.步骤
. https://docs.docker.com/engine/install/["查看 Docker 的安装说明"^]
+
按照步骤安装受支持的 Docker Engine 版本。请勿安装最新版本，因为控制台不支持它。

. 验证 Docker 是否已启用并正在运行。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====